### ISSUE TITLE
strange layer overlap case

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#1311] opened 2020-02-18 02:38 UTC
Here is an unusual example of notes in separate layers behaving properly and improperly in the same measure:

<img width="749" alt="Screen Shot 2020-02-17 at 6 26 18 PM" src="https://user-images.githubusercontent.com/3487289/74698844-f46cfa80-51b3-11ea-9f6c-2518e6f33308.png">

The first stem-down dotted chord is incorrectly superimposed with the notes in the top layer, but the second stem-down dotted half chord is correctly offset from the top layer notes.  I would expect both of them to be wrong or both to be correct, but not one of each 😜 

MEI data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-02-17T18:26:41" version="2.6.0-dev-eae5ad6">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001567395296">
    <score xml:id="score-0000001205571169">
     <scoreDef xml:id="scoredef-0000001542016441">
      <staffGrp xml:id="staffgrp-0000001231241230">
       <staffDef xml:id="staffdef-0000001665767692" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="G" line="2" />
        <keySig xml:id="keysig-L3F1" pname="f" mode="major" sig="1f" />
        <meterSig xml:id="metersig-L5F1" count="3" unit="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="0">
       <staff xml:id="staff-0000001843736635" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <chord xml:id="chord-L8F1" dur="4">
          <note xml:id="note-L8F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L8F1S2" oct="6" pname="f" accid.ges="n" />
         </chord>
         <chord xml:id="chord-L9F1" dur="4">
          <note xml:id="note-L9F1S1" oct="5" pname="e" accid="f" />
          <note xml:id="note-L9F1S2" oct="6" pname="e" accid="f" />
         </chord>
         <chord xml:id="chord-L10F1" dur="4">
          <note xml:id="note-L10F1S1" oct="5" pname="d">
           <accid xml:id="accid-L10F1S1" accid="n" func="caution" />
          </note>
          <note xml:id="note-L10F1S2" oct="6" pname="d" accid="n" />
         </chord>
         <chord xml:id="chord-L11F1" dur="4">
          <note xml:id="note-L11F1S1" oct="5" pname="c" accid.ges="n" />
          <note xml:id="note-L11F1S2" oct="6" pname="c" accid.ges="n" />
         </chord>
         <tuplet xml:id="tuplet-L12F1-L14F1" num="3" numbase="2" num.format="count">
          <chord xml:id="chord-L12F1" dur="4">
           <note xml:id="note-L12F1S1" oct="4" pname="b" accid.ges="f" />
           <note xml:id="note-L12F1S2" oct="5" pname="b" accid.ges="f" />
          </chord>
          <chord xml:id="chord-L13F1" dur="4">
           <note xml:id="note-L13F1S1" oct="4" pname="a" accid="f" />
           <note xml:id="note-L13F1S2" oct="5" pname="a">
            <accid xml:id="accid-L13F1S2" accid="f" func="caution" />
           </note>
          </chord>
          <chord xml:id="chord-L14F1" dur="4">
           <note xml:id="note-L14F1S1" oct="4" pname="g" accid="f" />
           <note xml:id="note-L14F1S2" oct="5" pname="g" accid.ges="f" />
          </chord>
         </tuplet>
        </layer>
        <layer xml:id="layer-L8F2N2" n="2">
         <chord xml:id="chord-L8F2" dots="1" dur="2">
          <note xml:id="note-L8F2S1" oct="5" pname="a" accid="f" />
          <note xml:id="note-L8F2S2" oct="6" pname="d" accid="f" />
         </chord>
         <chord xml:id="chord-L11F2" dots="1" dur="2">
          <note xml:id="note-L11F2S1" oct="5" pname="d" accid="f" />
          <note xml:id="note-L11F2S2" oct="5" pname="g" accid="f" />
         </chord>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L15" n="26">
       <staff xml:id="staff-L15F1N1" n="1">
        <layer xml:id="layer-L15F1N1" n="1">
         <chord xml:id="chord-L16F1" dur="4">
          <note xml:id="note-L16F1S1" oct="4" pname="f" accid.ges="n" />
          <note xml:id="note-L16F1S2" oct="5" pname="f" accid.ges="n" />
         </chord>
         <chord xml:id="chord-L17F1" dur="4">
          <note xml:id="note-L17F1S1" oct="4" pname="e" accid="f" />
          <note xml:id="note-L17F1S2" oct="5" pname="e" accid="f" />
         </chord>
         <chord xml:id="chord-L18F1" dur="4">
          <note xml:id="note-L18F1S1" oct="4" pname="d">
           <accid xml:id="accid-L18F1S1" accid="n" func="caution" />
          </note>
          <note xml:id="note-L18F1S2" oct="5" pname="d" accid="n" />
         </chord>
         <chord xml:id="chord-L19F1" dur="4">
          <note xml:id="note-L19F1S1" oct="4" pname="c" accid.ges="n" />
          <note xml:id="note-L19F1S2" oct="5" pname="c" accid.ges="n" />
         </chord>
         <tuplet xml:id="tuplet-L20F1-L22F1" num="3" numbase="2" num.format="count">
          <chord xml:id="chord-L20F1" dur="4">
           <note xml:id="note-L20F1S1" oct="3" pname="b" accid.ges="f" />
           <note xml:id="note-L20F1S2" oct="4" pname="b" accid.ges="f" />
          </chord>
          <chord xml:id="chord-L21F1" dur="4">
           <note xml:id="note-L21F1S1" oct="3" pname="a" accid="f" />
           <note xml:id="note-L21F1S2" oct="4" pname="a">
            <accid xml:id="accid-L21F1S2" accid="f" func="caution" />
           </note>
          </chord>
          <chord xml:id="chord-L22F1" dur="4">
           <note xml:id="note-L22F1S1" oct="3" pname="g" accid="f" />
           <note xml:id="note-L22F1S2" oct="4" pname="g" accid.ges="f" />
          </chord>
         </tuplet>
        </layer>
        <layer xml:id="layer-L15F2N2" n="2">
         <chord xml:id="chord-L16F2" dots="1" dur="2">
          <note xml:id="note-L16F2S1" oct="4" pname="a" accid="f" />
          <note xml:id="note-L16F2S2" oct="5" pname="d" accid="f" />
         </chord>
         <chord xml:id="chord-L19F2" dots="1" dur="2">
          <note xml:id="note-L19F2S1" oct="4" pname="d" accid="f" />
          <note xml:id="note-L19F2S2" oct="4" pname="g" accid="f" />
         </chord>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

**Comment by lpugin** [comment] 2020-02-18 07:41
The problem itself is the same as #1162, isn't it?

**Comment by craigsapp** [comment] 2020-02-18 13:44
> The problem itself is the same as #1162, isn't it?

Yes, it is related, although I am wondering why some of them are offset in this example while in #1162, all of the layer-crossings are not offset.

**Comment by lpugin** [comment] 2020-02-18 13:49
The one that are offset are because of the collision note heads (second interval) properly handled. The problem is when note heads to not collide. I am closing it since the reference from the other ticket is not given.

**Closed by lpugin** 2020-02-18 13:49 UTC
Labels: enhancement, low priority

**Comment by craigsapp** [comment] 2020-02-18 14:31
> second interval

that makes sense.
