### ISSUE TITLE
multiple syl per verse rendered on top of each other

### ISSUE THREAD

**Issue by andrewacashner** [rism-ch/verovio#938] opened 2018-10-17 17:28 UTC
Mutliple syllables `<syl>` in the same `<verse>` and `<note>` should be rendered consecutively separated by the specified connector (`@con`). Instead Verovio renders them to SVG on top of each other.

```
<mei>
  <!-- ... -->
  <note pname="a" oct="4" dur="2">
    <verse>
      <syl con="b">y</syl>
      <syl>a</syl>
    </verse>
  </note>
</mei>
```

Verovio does the right thing if I enter `<verse><syl>y_a</syl></verse>` but this is not what the MEI documentation recommends and for good reason.

**Comment by rettinghaus** [comment] 2018-10-17 19:51
Duplicate of #562

**Closed** 2018-10-17 22:02 UTC
