### ISSUE TITLE
Do not transpose unpitched notes

### ISSUE THREAD

**Issue by valeriyvan** [rism-ch/verovio#1520] opened 2020-06-26 10:11 UTC
Original mei file https://raw.githubusercontent.com/music-encoding/sample-encodings/master/MEI_4.0/Music/Complete_examples/Chopin_Mazurka.mei

Here page rendered with command: `./verovio -r ./data --transpose -F# Chopin_Mazurka.mei -p3`

![Chopin_Mazurka svg](https://user-images.githubusercontent.com/1630974/85846184-c02ec980-b7a5-11ea-8388-33e993916746.png)

Same page rendered without transposition:
![Chopin_Mazurka_003 svg](https://user-images.githubusercontent.com/1630974/85846384-04ba6500-b7a6-11ea-94a1-8ece1142bf8a.png)

**Comment by rettinghaus** [comment] 2020-06-26 10:20
looks like a transposition problem with grace notes, @craigsapp?

**Comment by craigsapp** [comment] 2020-06-26 16:17
@valeriyvan: you should distill music into minimal examples that still exhibit the problem.

```
         <note grace="unknown" dur="8" stem.dir="up" stem.mod="1slash"/>
          <chord xml:id="d814e1" dur="4" stem.dir="down">
              <note xml:id="d1e9565" pname="f" oct="5" accid.ges="s"/>
              <note xml:id="d1e9586" pname="c" oct="6" accid.ges="s"/>
           </chord>
```

The source of the problem is that the grace note has no pitch information, so it is incorrect to display it as an E4 in the original notation to begin with.  It would be good for the transposer to skip over notes that have no pitch information (this will also include unpatched drum parts).

The data set you cite for this example has been discussed before, and to summarize, it has lots of bugs.
The file also says it is MEI 4.0.0, but it is using `@stem.mod="1slash"`, instead use `@grace="unacc"` (so I am wondering if it is really MEI 4.0.0).   There are also alignment problems between layers in several measures.

Another transposition problem is that the data for the key signature:

```
<scoreDef meter.count="3" meter.unit="4" key.sig="3s">
```

does not encode the key, only the key signature (which could be either A major or F-sharp minor).  Therefore transposition by key tonic as your are doing will be incorrect.  Instead for such cases, transposition by interval is needed such as `M3` for a major third up.

----------------------------------------------

I see that I am the original encoder of this file:

```
          <bibl>
            <identifier type="URI"
              >http://kern.ccarh.org/cgi-bin/ksdata?l=users/craig/classical/chopin/mazurka&amp;file=mazurka06-1.krn&amp;f=xml</identifier>
            <title>Mazurka in F-sharp Minor op. 6,1</title>
            <imprint>
              <date isodate="2011-01-06"/>
              <respStmt>
                <corpName role="publisher">CCARH, Stanford University</corpName>
              </respStmt>
              <address>
                <addrLine>Center for Computer Research in Music and Acoustics</addrLine>
                <addrLine>Department of Music,</addrLine>
                <addrLine>Stanford University</addrLine>
                <addrLine>Stanford, California 94305-8180, USA</addrLine>
              </address>
            </imprint>
          </bibl>
```

The original Humdrum score: http://kern.ccarh.org/cgi-bin/ksdata?l=users/craig/classical/chopin/mazurka&file=mazurka06-1.krn

This is also on Github:

https://github.com/craigsapp/chopin-mazurkas
https://github.com/craigsapp/chopin-mazurkas/blob/master/kern/mazurka06-1.krn

A scan of the source edition is also on Github (Mikuli/Schirmer):
https://github.com/craigsapp/chopin-mazurkas/blob/master/reference-edition/mazurka06-1.pdf

Here is the grace note in question at the end of page 2:

<img width="214" alt="Screen Shot 2020-06-26 at 8 28 32 AM" src="https://user-images.githubusercontent.com/3487289/85874189-18a29e80-b787-11ea-9493-be15a241cf60.png">

This score was originally encoded in 2005 using SharpEye OMR, then exported to MusicXML, then translated to Humdrum.  Only rhythms and pitches were corrected and most grace notes were not encoded since SharpEye is not so great at them and it is difficult to add in the SharpEye editor.  The purposes of these encodings were for music analysis, such as to create keyscape pictures of the Chopin mazurkas:

http://extras.humdrum.org/man/mkeyscape/chopin-maz/index.html

Such as this one:

![mazurka06-1-large](https://user-images.githubusercontent.com/3487289/85876405-88665880-b78a-11ea-822c-a1b73c04e2ba.png)

Yellowish green is F# minor and the purple region is the relative major (A major).   The structure of the piece is ABAccA based on the repetition of the key patterns in the plot.

The data in this state was exported out of Humdrum with my Humdrum-to-MusicXML converter (which I mostly only spent two weeks on 20 years ago) and then into @pero's musicxml2mei converter, which obviously cannot convert grace notes (at least at the time).

Since then I have proofread the notational aspects of the original encoding (primarily slurs and grace notes), with the current version last edited 5 April 2020, and this can now be converted directly into MEI without an intermediate step through MusicXML and two buggy converters.  Here is a view of the proofread Humdrum score in [VHV](https://verovio.humdrum.org):

<img width="1271" alt="Screen Shot 2020-06-26 at 8 57 18 AM" src="https://user-images.githubusercontent.com/3487289/85876971-5275a400-b78b-11ea-95c0-76c45e8fa17a.png">

I am showing the Scores menu which has an entry for these mazurkas.  You can type alt-m in the editor to get the MEI conversion of this data.

Here is a direct link to the score in VHV:

http://verovio.humdrum.org/?file=github:craigsapp/chopin-mazurkas/kern/mazurka06-1.krn


----------------------------------------------


Otherwise, there is no problem with grace note transposition, per se:

Test:

<img width="323" alt="Screen Shot 2020-06-26 at 8 31 52 AM" src="https://user-images.githubusercontent.com/3487289/85878552-be590c00-b78d-11ea-8caa-9e71a8604c12.png">


```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-06-26T08:34:57" version="3.0.0-dev-4714301-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001020637336">
    <score xml:id="score-0000001899817563">
     <scoreDef xml:id="scoredef-0000000231074616">
      <staffGrp xml:id="staffgrp-0000000625286075">
       <staffDef xml:id="staffdef-0000000241721587" n="1" lines="5">
        <clef xml:id="clef-0000000276757636" shape="G" line="2" />
        <keySig xml:id="keysig-L2F1" accid="s" pname="f" mode="minor" sig="3s" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="43">
       <staff xml:id="staff-0000000500843731" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L5F1" dur="8" oct="5" pname="g" grace="unacc" accid.ges="s" />
         <chord xml:id="chord-L6F1" dur="4">
          <note xml:id="note-L6F1S1" oct="5" pname="f" accid.ges="s" />
          <note xml:id="note-L6F1S2" oct="6" pname="c" accid.ges="s" />
         </chord>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

And after `veorvio --transpose F#  file.txt -atmei` (the origin file needs to be called `file.txt` so that a new `file.mei` can be written), there should be no change in the musical content because the music is already in F# minor, so the transposition will be to the same pitches (or ideally the transposer should note that the transposition is to the unison, so it does not try to do any transposing).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-06-26T08:34:57" version="3.0.0-dev-4714301-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001020637336">
    <score xml:id="score-0000001899817563">
     <scoreDef xml:id="scoredef-0000000231074616">
      <staffGrp xml:id="staffgrp-0000000625286075">
       <staffDef xml:id="staffdef-0000000241721587" n="1" lines="5">
        <clef xml:id="clef-0000000276757636" shape="G" line="2" />
        <keySig xml:id="keysig-L2F1" accid="s" pname="f" mode="minor" sig="3s" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="43">
       <staff xml:id="staff-0000000500843731" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L5F1" dur="8" oct="5" pname="g" grace="unacc" accid.ges="s" />
         <chord xml:id="chord-L6F1" dur="4">
          <note xml:id="note-L6F1S1" oct="5" pname="f" accid.ges="s" />
          <note xml:id="note-L6F1S2" oct="6" pname="c" accid.ges="s" />
         </chord>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

Here is a test of transposing it to C minor:

<img width="322" alt="Screen Shot 2020-06-26 at 8 44 35 AM" src="https://user-images.githubusercontent.com/3487289/85875618-5bfe0c80-b789-11ea-890d-51a6f4361ae7.png">

```bash
verovio --transpose C file.mei -atmei
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-06-26T08:34:57" version="3.0.0-dev-4714301-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001020637336">
    <score xml:id="score-0000001899817563">
     <scoreDef xml:id="scoredef-0000000231074616">
      <staffGrp xml:id="staffgrp-0000000625286075">
       <staffDef xml:id="staffdef-0000000241721587" n="1" lines="5">
        <clef xml:id="clef-0000000276757636" shape="G" line="2" />
        <keySig xml:id="keysig-L2F1" accid="n" pname="c" mode="minor" sig="3f" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="43">
       <staff xml:id="staff-0000000500843731" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L5F1" dur="8" oct="5" pname="d" grace="unacc" accid.ges="n" />
         <chord xml:id="chord-L6F1" dur="4">
          <note xml:id="note-L6F1S1" oct="5" pname="c" accid.ges="n" />
          <note xml:id="note-L6F1S2" oct="5" pname="g" accid.ges="n" />
         </chord>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

**Closed** 2020-06-29 11:37 UTC
Labels: enhancement
