### ISSUE TITLE
problem with using system break

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#113] opened 2015-06-17 20:00 UTC
Using the `<sb/>` element only works correctly if you use it consistently. In cases where it's never used, verovio formats the music itself, but if `<sb/>` is used once (and only once, for example), the verovio relies on it for the rest of the piece.
Here, for example, if you use it after the first bar, it groups the entire rest of the piece together, whereas if you don't use it at all it formats it correctly.

![screen shot 2015-06-05 at 11 29 14 am](https://cloud.githubusercontent.com/assets/11529868/8217096/1461fa30-1509-11e5-926e-dc35b49141d7.png)

The same thing happens at the end and in the middle of pieces, depending on where you put the element.
![screen shot 2015-06-05 at 11 23 36 am](https://cloud.githubusercontent.com/assets/11529868/8217199/f0de6250-1509-11e5-8962-3321eb7c798c.png)

or:
![screen shot 2015-06-05 at 11 29 29 am](https://cloud.githubusercontent.com/assets/11529868/8217198/f0dab77c-1509-11e5-9270-27618cd9ef32.png)

**Comment by lpugin** [comment] 2015-06-18 07:20
Yes, this is the expected behavior. What else would you expect?

**Comment by ahankinson** [comment] 2015-06-18 11:39
I don't think I would expect all the notes on top of each other! :)

**Comment by lpugin** [comment] 2015-06-18 21:37
Obviously. But What would you expect in terms of system breaks? Would you expect Verovio to add some system breaks when the staff is full plus make system breaks when there is one in the encoding? Then can end up with a staff with, let's say six measures, and then a staff with one single measure spread out because Verovio added a system break before the measure and there is one /sb after it. This would be very weird. It seems to me that the issue pointed here is mostly inconsistency in the encoding. You can always choose the --ignore-layout option that would ignore all /sb (and /pb). So unless we can come up with a clearly defined behavior to implement for cases where there is /sb inconsistently I would rather close this issue.

**Comment by ahankinson** [comment] 2015-06-18 21:41
Does verovio know when it reaches the edge of a page? I always assumed that it inserts an implicit system break, unless there is an explicit one. The example of there being six measures and then one seems like the desired behaviour.

**Comment by lpugin** [comment] 2015-06-19 12:53
Yes, it does. We could make it as you describe, but am not convinced it will be very useful. Inconsistent /sb make sense with a specific layout algorithm and a particular page size. If you change any of these it is quite likely that you will end up with unexpected results. Example: you encode a piece and the notation software puts 8 measures in the first staff. You add an explicit /sb after measure 7 because you think it is better. Now you load this in Verovio, and because of the difference in the layout algorithm, or the screen size, it reaches the end of the staff after measure 6. Then, because of the explicit /sb you will end up with only measure 7 on the second staff. Do you see what I mean?

**Closed** 2015-06-22 19:05 UTC
