### ISSUE TITLE
Error reporting leaves much to be desired

### ISSUE THREAD

**Issue by donbyrd** [rism-ch/verovio#180] opened 2016-05-11 20:44 UTC
Verovio's error reporting leaves much to be desired. For example, in mensural notation, if there's no <mensur>, it gives the [Warning] "No current mensur for calculating duration" for every note, with no indication of where in the input the problem is; even if it said where the problem is, this would be unsatisfactory because other warnings could easily get lost in a sea of "No current mensur..." messages.

A much simpler flaw is that some messages that the user clearly should know about are level [Debug], but they should be level [Warning], if not higher. For example, two of the messages iomei.cpp can give about elements being ignored are calls to LogDebug;  the other two are calls to LogWarning.

**Comment by ahankinson** [comment] 2016-05-11 20:46
Does validating the MEI file give you a better idea of where the problem is?

**Comment by lpugin** [comment] 2016-05-11 21:10
This should indeed be improved. One option could be to have a pedantic mode and make it fail straight away when something wrong is encountered. (Up to know the approach is more to try to go through the process.) I am not sure what this would bring. I would rather try to have validation improved with Schematron, which for the case you are mentioning with the mensur missing would be the way to go. But if you can see how to improve the messages and to  make them consistent, please go ahead.

**Comment by pe-ro** [comment] 2016-05-11 21:21
@donbyrd: Did you mean to say "if there's no mensur attribute, it gives the [Warning] ..."?

I agree with @lpugin that building more "knowledge" into MEI about processing requirements via Schematron (within reasonable limits, of course) sounds like a good way forward.

**Comment by donbyrd** [comment] 2016-05-11 23:08
I haven't tried validating the MEI file. Regardless, I agree that improved validation with Schematron is a good idea. But it's surely not a complete solution, especially since we can't assume that all users will validate every MEI file before using Verovio on it. Even after running Verovio, they might think their problems are less serious than they really are because they haven't noticed messages about serious errors buried in less serious ones.

The idea of a "pedantic" -- I'd say "strict" -- mode is a good one, too. But again, it's not a complete solution, even coupled with improved validation. This is a non-trivial problem, and I think it'll take awhile to be solved properly.

As for consistency, I don't think we're actually using the syslog() function, though I suspect we _should_ be. But we certainly seem to be using its evels as defined in e.g., the BSD Library Functions Manual, Section 3. According to that, the levels are ordered from least to most serious LOG_DEBUG, LOG_INFO, LOG_NOTICE, LOG_WARNING, LOG_ERR, LOG_CRIT, LOG_ALERT, LOG_EMERG; and it gives pretty clear definitions of what they mean. Their definitions seem well-thought-out, and I think we should follow them. That'd also be a very partial solution, but I'll start doing that as I run across messages.

**Comment by pe-ro** [comment] 2016-05-12 01:38
I can't comment on the coding of Verovio, but is it unrealistic to expect Verovio to work only on valid files?  Valid files are the point of using a schema, after all.  Or do you expect Verovio to work in **quirks mode** like a badly-designed browser?  ;-)

**Comment by donbyrd** [comment] 2016-05-12 01:57
Sorry for the unclarity. Of course it's not unrealistic to expect Verovio to work only on valid files, but I think it's unrealistic to think users will always check that their files are valid before feeding them into Verovio. Besides, many files -- like my mensural-notation example without a <mensur> -- are likely to be valid MEI but still present problems. Therefore it's important that Verovio make it as clear as possible to the user what the problems in the file are. I don't think burying messages about illegal elements (in my case, <barline> where I meant <barLine>) in a hundred identical messages about something unrelated qualifies as "making it as clear as possible".

**Comment by lpugin** [comment] 2016-05-12 06:29
Users should strongly be encourage to check their files are valid, at least when something goes wrong. So there is no point rebuilding the schema within Verovio.

However, validation with not solve all the issues either, so we certainly need to improve the messages. I am not convinced we need more levels that what we have (DEBUG, INFO, WARNING, ERROR) since it is already not so easy to decide what a message should be. Before we add more level we should try to see how to improve it. In the JavasScript version, a message will be shown only once (and not repeated if it appears again). This is probably something we can have in the command line output too.

**Comment by donbyrd** [comment] 2016-05-12 10:28
First, I didn't mean to suggest that we use more levels; I was just drawing attention to the syslog(3) documentation, and suggesting we be careful to use DEBUG, INFO, WARNING, and ERROR according to their definitions. They say:
 LOG_ERR       Errors.
 LOG_WARNING   Warning messages.
 LOG_NOTICE    Conditions that are not error conditions, but should possibly be handled specially.
 LOG_INFO      Informational messages.
 LOG_DEBUG     Messages that contain information normally of use only when debugging a program.

Well, I guess we merge NOTICE into INFO, which seems fine. So our definition of INFO would be "Informatiional messages and conditions that are not error conditions, but should possibly be handled specially". (And we say ERROR instead of ERR, of course.)

Second, just showing a given message once isn't ideal either; as a user, I'd really like to know if something occurred once or 90 times. But it can also be very useful to know where each occurrence was! A compromise solution I rather like is to have the program wait till it's about to quit and then say something like, for each message:

   [Warning] No current mensur for calculating duration: occurred 90 times; the first was on line 23

If the user then looks at line 23, they can fix it, and it might be obvious they need to change similar things elsewhere; if not, re-running will tell them where the next occurence is (probably nowhere for a warning about no current mensur, of course).

**Comment by lpugin** [comment] 2016-05-12 18:35
Showing the number of times an message occurs is a good idea. Showing the line number is trickier since the XML is parse and we don't really have line numbers.

What I usually do is show the xml:id. (Now this is helpful only if the MEI file has xml:ids, which is not always the case.). So one way to improve it would be to store each message with a list of xml:ids, and then have an option to show ids (or not) in the output.

**Comment by pe-ro** [comment] 2016-05-12 21:15
Another possibility is to display an error location based on the structure of the data, for instance "m. 3, 3rd note",  if one has measures, that is. :-)  Perhaps something based on page and staff instead?  In any case, these are things that are relatively easy to get from the XML and that one can be assured will be in the data.

**Comment by lpugin** [comment] 2016-05-13 07:52
Not having the xml:ids in the original MEI file is actually not a so much of an issue. It is always possible to export the MEI file from Verovio where then we can see the xml:ids assigned by Verovio when they are not provided in the original file.

**Comment by donbyrd** [comment] 2016-05-15 14:03
Attached is a screenshot of Nightingale's Score Info dialog; note the statements about duration problems, empty staff-measures, and out-of-range notes.

Starting with this kind of report, we could also give users full details with much less chance of their overlooking important problems by saving a full set messages on a file,
![scoreinfo](https://cloud.githubusercontent.com/assets/1672175/15274602/442edb8a-1a84-11e6-8e5d-aac247baab48.png)
 as well as writing the summary to stdout or stderr.

**Comment by lpugin** [comment] 2016-08-05 07:55
I am not sure what this type of report would bring. And for most of them it is actually straight forward to get them with xPath queries directly on the MEI file.

**Closed** 2017-01-16 15:04 UTC
Labels: enhancement
