### ISSUE TITLE
MusicXML import segfaults when importing chords with bTrem style tremolos

### ISSUE THREAD

**Issue by th-we** [rism-ch/verovio#1596] opened 2020-08-06 06:59 UTC
```xml
<?xml version="1.0" encoding="UTF-8"?>
<score-partwise version="3.0">
   <work>
      <work-title/>
   </work>
   <part-list>
      <score-part id="P6">
         <part-name>Oboe 1.2</part-name>
      </score-part>
   </part-list>
   <part id="P6">
      <measure number="1392" width="265">
         <attributes>
            <divisions>256</divisions>
            <key color="#000000">
               <fifths>-2</fifths>
               <mode>major</mode>
            </key>
            <time color="#000000">
               <beats>6</beats>
               <beat-type>8</beat-type>
            </time>
            <staves>1</staves>
            <clef number="1" color="#000000">
               <sign>G</sign>
               <line>2</line>
            </clef>
         </attributes>
         <print/>
         <note color="#000000" default-x="15" default-y="-65">
            <pitch>
               <step>F</step>
               <octave>4</octave>
            </pitch>
            <duration>768</duration>
            <voice>1</voice>
            <type>half</type>
            <dot/>
            <stem>down</stem>
            <staff>1</staff>
            <notations>
               <ornaments>
                  <tremolo type="single">1</tremolo>
               </ornaments>
            </notations>
         </note>
         <note color="#000000" default-x="15">
            <chord/>
            <pitch>
               <step>F</step>
               <octave>5</octave>
            </pitch>
            <duration>512</duration>
            <type>half</type>
            <dot/>
            <staff>1</staff>
            <notations>
               <ornaments>
                  <tremolo type="single">1</tremolo>
               </ornaments>
            </notations>
         </note>
      </measure>
   </part>
</score-partwise>
```

**Comment by craigsapp** [comment] 2020-08-06 18:04
The problem is happening in ReadMusicXmlNote.  Here is the function stack at the time of the crash:

```
vrv::MusicXmlInput::ReadMusicXmlNote
vrv::MusicXmlInput::ReadMusicXmlMeasure
vrv::MusicXmlInput::ReadMusicXmlPart
vrv::MusicXmlInput::ReadMusicXml
vrv::MusicXmlInput::Import
vrv::Toolkit::LoadData
vrv::Toolkit::LoadFile
main + 5637 
```

**Comment by rettinghaus** [comment] 2020-09-24 15:46
This has been fixed in the meantime, now it renders fine.

**Comment by rettinghaus** [comment] 2020-09-24 15:48
![image](https://user-images.githubusercontent.com/7693447/94168583-14714480-fe8e-11ea-91f6-e33ba89cba63.png)

**Comment by rettinghaus** [comment] 2020-10-05 13:07
@craigsapp @lpugin please close.

**Closed** 2020-10-05 14:25 UTC
Labels: bug, musicxml
