### ISSUE TITLE
fontsize uses values as point size

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#486] opened 2017-02-23 22:01 UTC
every value set in `@fontsize` gets interpreted as a `pt` value. At least relative values given as percentage of normal size should be considered correctly. 

![fontsize](https://cloud.githubusercontent.com/assets/7693447/23281031/dfe37b9a-fa1b-11e6-89a4-d200b156f70e.png)

```xml
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title/>
      </titleStmt>
      <pubStmt/>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef meter.count="4" meter.unit="4">
            <staffGrp>
              <staffDef n="1" clef.line="3" clef.shape="C" lines="5"/>
            </staffGrp>
          </scoreDef>
          <section>
            <measure n="2">
              <staff n="1">
                <layer n="1">
                  <note xml:id="n04" dur="4" oct="4" pname="g"/>
                  <note xml:id="n05" dur="4" oct="4" pname="g"/>
                  <note xml:id="n06" dur="4" oct="4" pname="g"/>
                  <note xml:id="n07" dur="4" oct="4" pname="g"/>
                </layer>
              </staff>
              <dir startid="#n04" place="above"><rend fontsize="210pt">210pt</rend></dir>
              <dir startid="#n05" place="above"><rend fontsize="54.32%">54.32%</rend></dir>
              <dir startid="#n06" place="above"><rend fontsize="72%">72%</rend></dir>
              <dir startid="#n07" place="above"><rend fontsize="2.3mm">2.3mm</rend></dir>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

**Comment by rettinghaus** [comment] 2017-02-23 22:02
Sorry, I'll try again …

**Comment by lpugin** [comment] 2017-02-24 07:44
I pushed a preliminary implementation to https://github.com/rism-ch/verovio/tree/develop-fontsize (and to https://github.com/rism-ch/libmei/tree/develop-fontsize for the corresponding changes to LibMEI configuration)

It now does only the same as before. That is reading all values as points. We need to have the StrToFontSize and FontSizeToStr (in att.h and att.cpp) changes in order to identify other types.

The change in view_text.cpp show hows then to handle the fontsize.

**Comment by craigsapp** [comment] 2017-02-27 07:52
Can font sizes be given in vu's?

**Comment by pe-ro** [comment] 2017-02-27 14:55
> Can font sizes be given in vu's?

Not currently.  Is that needed?

**Comment by craigsapp** [comment] 2017-02-27 15:40
It is sort of needed.  How do percentage sizes work and what is 100% size?

**Comment by pe-ro** [comment] 2017-02-27 15:50
100% is whatever is specified by `@music.size` attached to `<scoreDef>` or `@text.size` attached to `<scoreDef>`, `<staffDef>` or `<layerDef>`. Obviously, the sizes given there can't also be expressed in relative units, unless they're relative to something that ultimately resolves to an absolute measurement.  For example, `<scoreDef text.size="10vu">` is ok as long as somewhere a `vu` is defined as "5mm".

**Comment by craigsapp** [comment] 2017-02-27 16:31
In SCORE, all font sizes are stored relative to the staff size.  A text size of 100% (1.0) means that the x-height of the text is 2 vu.  If the staff size is set to 100% of the default size, and the printing size for the page is 100% of the default print size, this means 13.56 points.

Shrinking the size of the staff will also shrink the absolute size of the font, but its vu size on the staff remains constant as illustrated in the figure below where the bottom staff has a size of 50%, but the text size on both staves is 100%:

<img width="864" alt="screen shot 2017-02-27 at 8 09 24 am" src="https://cloud.githubusercontent.com/assets/3487289/23369057/ee7feac0-fcc4-11e6-9478-eadfa3d4f6a6.png">

SCORE allows you to set a physical point size, but assumes that the print size will be 100%.  For example if I set the point size of the text to 12 on the top staff, the vu size will become 88%, and if the staff is resized to 50% then the point size would become 6 pt.  I could set the font size to 12 pt on the 50% sized staff and the vu size would become 1.78.  So note that the vu size is dependent on the staff size to which the text is attached.  If the text were not attached to a staff (such as page-specific text), then absoulte point sizes are more useful to reference directly.

<img width="861" alt="screen shot 2017-02-27 at 8 24 41 am" src="https://cloud.githubusercontent.com/assets/3487289/23369535/8530e374-fcc6-11e6-884c-946dc08b5ee9.png">

**Comment by lpugin** [comment] 2018-02-05 09:36
I am not sure about pt values would mean but other font size options are now supported (percent and terms) so I am closing this issue.

**Closed by lpugin** 2018-02-05 09:36 UTC
Labels: feature request, low priority

**Comment by rettinghaus** [comment] 2018-02-07 14:33
Funny thing is: you can now specify lyric size with Verovio CLI, but you can't do it with `@fontsize`, as `data.FONTSIZE` won't allow MEI units. Shouldn't that be changed in 4.0? 

And as the `--lyric-size` command affects all text (also `<dir>` and `<tempo>`) shouldn't this command renamed to `--fontsize` (according to attribute name)?

**Comment by lpugin** [comment] 2018-02-07 14:41
> Funny thing is: you can now specify lyric size with Verovio CLI, but you can't do it with @fontsize, as data.FONTSIZE won't allow MEI units. Shouldn't that be changed in 4.0?

Yes, this is why is it currently an option and `@fontsize` is not implememeted. You can set a `pt` value but I have not idea how this should be interpreted. Maybe @pe-ro has some clues about it?

> And as the --lyric-size command affects all text (also <dir> and <tempo>) shouldn't this command renamed to --fontsize (according to attribute name)?

I would rather add an option for each of them.

**Comment by rettinghaus** [comment] 2018-02-07 14:51
> I would rather add an option for each of them.

There are already so many options now, why not take three: 
`--fontsize`
`--fontsize-lyrics`
`--fontsize-dir`

**Comment by lpugin** [comment] 2018-02-07 14:56
The problem is not so much adding options but more adding the complexity option levels. With your suggestion we need to have a way to say that `fontsize-lyrics` is not set, and then do some look-up for picking `fontsize-lyrics` or `fontsize` accodingly. This was the same as with `page-margin` and `page-margin-left`. I am not sure I want to go down that road and would prefer just to add `--tempo-size` and '--dir-size`.
