### ISSUE TITLE
Python3 Installation not working on Mac

### ISSUE THREAD

**Issue by karend27** [rism-ch/verovio#600] opened 2017-05-17 17:09 UTC
Hello,

I'm trying to install the python toolkit on my MacBook, using python3. I've installed swig using brew successfully, but when I try to run the command on the installation page, I get this error:

```
MacBook-Pro-4:python karen$ python3 setup.py build_ext
running build_ext
building '_verovio' extension
swigging verovio.i to verovio_wrap.cpp
swig -python -c++ -o verovio_wrap.cpp verovio.i
/usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/usr/local/include -I../include -I../include/vrv -I../include/json -I../include/midi -I../include/hum -I../include/pugi -I../include/utf8 -I../include/win32 -I../libmei -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c ../src/accid.cpp -o build/temp.macosx-10.6-intel-3.6/../src/accid.o -DPYTHON_BINDING -std=c++11 -Wno-write-strings -Wno-overloaded-virtual -Wno-unused-private-field
In file included from ../src/accid.cpp:8:
In file included from ../include/vrv/accid.h:11:
In file included from ../include/vrv/layerelement.h:11:
In file included from ../libmei/atts_shared.h:18:
In file included from ../include/vrv/att.h:16:
../include/vrv/vrvdef.h:216:26: error: no member named 'tuple' in namespace
      'std'
typedef std::vector<std::tuple<Alignment *, Alignment *, int> > ArrayOfA...
                    ~~~~~^
../include/vrv/vrvdef.h:216:32: error: 'Alignment' does not refer to a value
typedef std::vector<std::tuple<Alignment *, Alignment *, int> > ArrayOfA...
                               ^
../include/vrv/vrvdef.h:194:7: note: declared here
class Alignment;
      ^
../include/vrv/vrvdef.h:216:43: error: expected expression
typedef std::vector<std::tuple<Alignment *, Alignment *, int> > ArrayOfA...
                                          ^
../include/vrv/vrvdef.h:216:63: error: expected unqualified-id
typedef std::vector<std::tuple<Alignment *, Alignment *, int> > ArrayOfA...
                                                              ^
In file included from ../src/accid.cpp:17:
../include/vrv/functorparams.h:272:5: error: unknown type name
      'ArrayOfAdjustmentTuples'
    ArrayOfAdjustmentTuples m_overlapingSyl;
    ^
5 errors generated.
error: command '/usr/bin/clang' failed with exit status 1

```

Do you know how I could fix this? Thank you very much.

**Comment by lpugin** [comment] 2017-05-18 08:06
Anybody can help on this? I am using Python 2.7

**Comment by ahankinson** [comment] 2017-05-18 08:09
I'll see if I can give it a shot.

**Comment by ahankinson** [comment] 2017-05-18 13:02
The error you're getting may be from having an outdated compiler on your system, since `std::tuple` is available with C++11. Could you copy and paste the output of the following command to verify this?

`clang --version`

---

I wasn't able to reproduce the specific problem, but I did find another problem with building for Python 3. 

Adding `-DNO_HUMDRUM_SUPPORT` to the setup.py `EXTRA_COMPILE_ARGS` fixed a problem where I was getting a symbol not found error:

`Symbol not found: __ZN3hum17Tool_musicxml2hum7convertERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERN4pugi12xml_documentE`

@craigsapp any ideas?

**Comment by karend27** [comment] 2017-05-18 14:41
Thanks for looking into this. Here is the response to clang version:

```
MacBook-Pro-4:~ karen$ clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
MacBook-Pro-4:~ karen$
```

**Comment by ahankinson** [comment] 2017-05-18 16:01
I've been able to replicate your problem, which seems to be caused by not having access to the C++11 standard library. If you try to compile it without `--std=c++11` you get your exact error. 

The first thing you can try is to install XCode from the Mac App Store. That should give you the required headers in the right place.

**Comment by lpugin** [comment] 2017-05-21 10:36
@karend27 can I close the issue?

**Comment by karend27** [comment] 2017-05-22 15:39
Hi Laurent
Yes, you can close the issue - I have installed XCode (thanks Andrew) - I think I still have to fiddle with things a bit but if I encounter another problem I will start a new issue - thanks.

**Comment by lpugin** [comment] 2017-05-23 08:39
OK

**Closed by lpugin** 2017-05-23 08:39 UTC
Labels: documentation

**Comment by karend27** [comment] 2017-05-25 16:07
Hi,
Sorry, looks like even after installation of Xcode still getting same error. 

```
MacBook-Pro-5:python karen$ clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
MacBook-Pro-5:python karen$ python3 setup.py build_ext
running build_ext
building '_verovio' extension
swigging verovio.i to verovio_wrap.cpp
swig -python -c++ -o verovio_wrap.cpp verovio.i
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/usr/local/include -I../include -I../include/vrv -I../include/json -I../include/midi -I../include/hum -I../include/pugi -I../include/utf8 -I../include/win32 -I../libmei -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c ../src/accid.cpp -o build/temp.macosx-10.6-intel-3.6/../src/accid.o -DPYTHON_BINDING -std=c++11 -Wno-write-strings -Wno-overloaded-virtual -Wno-unused-private-field
In file included from ../src/accid.cpp:8:
In file included from ../include/vrv/accid.h:11:
In file included from ../include/vrv/layerelement.h:11:
In file included from ../libmei/atts_shared.h:18:
In file included from ../include/vrv/att.h:16:
../include/vrv/vrvdef.h:216:26: error: no member named 'tuple' in namespace
      'std'
typedef std::vector<std::tuple<Alignment *, Alignment *, int> > ArrayOfA...
                    ~~~~~^
../include/vrv/vrvdef.h:216:32: error: 'Alignment' does not refer to a value
typedef std::vector<std::tuple<Alignment *, Alignment *, int> > ArrayOfA...
                               ^
../include/vrv/vrvdef.h:194:7: note: declared here
class Alignment;
      ^
../include/vrv/vrvdef.h:216:43: error: expected expression
typedef std::vector<std::tuple<Alignment *, Alignment *, int> > ArrayOfA...
                                          ^
../include/vrv/vrvdef.h:216:63: error: expected unqualified-id
typedef std::vector<std::tuple<Alignment *, Alignment *, int> > ArrayOfA...
                                                              ^
In file included from ../src/accid.cpp:17:
../include/vrv/functorparams.h:272:5: error: unknown type name
      'ArrayOfAdjustmentTuples'
    ArrayOfAdjustmentTuples m_overlapingSyl;
    ^
5 errors generated.
error: command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang' failed with exit status 1
```
